
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.TreeView widgetTreeview;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Button refreshButton;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView detailsTextView;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 907;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.widgetTreeview = new global::Gtk.TreeView ();
		this.widgetTreeview.CanFocus = true;
		this.widgetTreeview.Name = "widgetTreeview";
		this.scrolledwindow1.Add (this.widgetTreeview);
		this.hpaned1.Add (this.scrolledwindow1);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.scrolledwindow1]));
		w2.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.refreshButton = new global::Gtk.Button ();
		this.refreshButton.CanFocus = true;
		this.refreshButton.Name = "refreshButton";
		this.refreshButton.UseUnderline = true;
		this.refreshButton.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.vbox1.Add (this.refreshButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.refreshButton]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.detailsTextView = new global::Gtk.TextView ();
		this.detailsTextView.CanFocus = true;
		this.detailsTextView.Name = "detailsTextView";
		this.GtkScrolledWindow.Add (this.detailsTextView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 1;
		this.hpaned1.Add (this.vbox1);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1304;
		this.DefaultHeight = 732;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.refreshButton.Clicked += new global::System.EventHandler (this.onRefreshClicked);
	}
}
